# This is a basic workflow to help get started with Actions

name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pistman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run API Tests
        run: newman run "Restful Booker BVT.postman_collection.json" -e Production.postman_environment.json
